In [2]:
import numpy as np

In [3]:
ab=np.array([2,3,4,5,6])
print(ab.ndim)

1


In [4]:
ab=np.array([[2,3,4,5,6]])
print(ab.ndim)

2


In [6]:
ab=np.array(25)
print(ab.ndim)

0


In [9]:
ab=np.array([[2,3,4,5,6],[21,31,41,51,61]])
print(ab.ndim)

2


In [10]:
for x in ab:
    print(x)

[2 3 4 5 6]
[21 31 41 51 61]


In [11]:
ab=np.array([[[2,3,4,5,6],[21,31,41,51,61]]])
print(ab.ndim)

3


In [13]:
for x in ab:
    for y in x:
        for y1 in y:
            print(y1)

2
3
4
5
6
21
31
41
51
61


In [14]:
ab=np.array([2,3,4,5,6,21,31,41,51,61])
print(ab.ndim)

1


In [15]:
print(len(ab))

10


In [16]:
ab=np.array([2,3,4,5,6,21,31,41,51,61])
ab1=ab.reshape(2,5)
print(ab1)

[[ 2  3  4  5  6]
 [21 31 41 51 61]]


In [17]:
ab=np.array([2,3,4,5,6,21,31,41,51,61])
ab1=ab.reshape(5,2)
print(ab1)

[[ 2  3]
 [ 4  5]
 [ 6 21]
 [31 41]
 [51 61]]


In [18]:
ab=np.array([2,3,4,5,6,21,31,41,51,61])
ab1=ab.reshape(1,5,2)
print(ab1)

[[[ 2  3]
  [ 4  5]
  [ 6 21]
  [31 41]
  [51 61]]]


In [19]:
ab=np.array([2,3,4,5,6,21,31,41,51,61])
ab1=np.mean(ab)
ab1

22.5

In [20]:
ab=np.array([2,3,4,5,6,21,31,41,51,61])
ab1=np.max(ab)
ab1

61

In [21]:
ab=np.array([2,3,4,5,6,21,31,41,51,61])
ab1=np.min(ab)
ab1

2

In [24]:
ab=np.array([2,3,4,5,6,21,31,41,51,61])
ab1=np.var(ab)
ab1

443.25

In [25]:
ab=np.array([2,3,4,5,6,21,31,41,51,61])
ab1=np.std(ab)
ab1

21.0535032714273

In [26]:
ab=np.array([2,3,4,5,6,21,31,41,51,61])
ab1=np.sum(ab)
ab1

225

In [27]:
# Array Spliting 

In [29]:
ab=np.array([2,3,4,5,6,21,31,41,51,61])
ab1=np.array_split(ab,5)
ab1

[array([2, 3]),
 array([4, 5]),
 array([ 6, 21]),
 array([31, 41]),
 array([51, 61])]

In [30]:
ab=np.array([2,3,4,5,6,21,31,41,51,61])
ab1=np.array_split(ab,15)
ab1

[array([2]),
 array([3]),
 array([4]),
 array([5]),
 array([6]),
 array([21]),
 array([31]),
 array([41]),
 array([51]),
 array([61]),
 array([], dtype=int32),
 array([], dtype=int32),
 array([], dtype=int32),
 array([], dtype=int32),
 array([], dtype=int32)]

In [31]:
print(ab1[7])

[41]


In [32]:
ab=np.array([2,3,4,5,6,21,31,41,51,61])
ab1=np.array_split(ab,3)
ab1

[array([2, 3, 4, 5]), array([ 6, 21, 31]), array([41, 51, 61])]

In [33]:
ab=np.array([2,3,4,5,6,21,31,41,51,61])
ab1=np.array_split(ab,9)
ab1

[array([2, 3]),
 array([4]),
 array([5]),
 array([6]),
 array([21]),
 array([31]),
 array([41]),
 array([51]),
 array([61])]

In [ ]:
ab=np.array([2,3,4,5,6,21,31,41,51,61])
ab1=np.array_split(ab,9)
ab1

In [34]:
# Array Searching

In [41]:
ab=np.array([12,21,43,54,45,36,27,18,19,10])
ab1=np.where(ab<=40)
ab1

(array([0, 1, 5, 6, 7, 8, 9], dtype=int64),)

In [39]:
ab=np.array([12,21,43,54,45,36,27,18,19,10])
ab1=np.where(ab%2==1)
ab1

(array([1, 2, 4, 6, 8], dtype=int64),)

In [42]:
# Array joining

In [43]:
ab1=np.array([2,3,4,5])
ab2=np.array([12,131,141,15])
ab3=np.concatenate((ab1,ab2))
ab3

array([  2,   3,   4,   5,  12, 131, 141,  15])

In [48]:
ab1=np.array([[2,3],[4,5]])
ab2=np.array([[12,131],[141,15]])
ab3=np.concatenate((ab1,ab2),axis=1)
ab3

array([[  2,   3,  12, 131],
       [  4,   5, 141,  15]])

In [47]:
ab1=np.array([[2,3],[4,5]])
ab2=np.array([[12,131],[141,15]])
ab3=np.concatenate((ab1,ab2))
ab3

array([[  2,   3],
       [  4,   5],
       [ 12, 131],
       [141,  15]])

In [49]:
ab1=np.array([[2,3,4],[1,4,5]])
ab2=np.array([[12,131],[141,15]])
ab3=np.concatenate((ab1,ab2),axis=1)
ab3

array([[  2,   3,   4,  12, 131],
       [  1,   4,   5, 141,  15]])

In [50]:
# Array Sorting 

In [51]:
ab=np.array([12,21,43,54,45,36,27,18,19,10])
ab1=np.sort(ab)
ab1

array([10, 12, 18, 19, 21, 27, 36, 43, 45, 54])

In [53]:
ab=np.array([12,21,43,54,45,36,27,18,19,10])
ab1=-np.sort(-ab)
ab1

array([54, 45, 43, 36, 27, 21, 19, 18, 12, 10])

In [55]:
ab=np.array([12,21,43,54,45,36,27,18,19,10])
ab1=-np.sort(-ab)
ab1

array([54, 45, 43, 36, 27, 21, 19, 18, 12, 10])

In [58]:
ab=np.array([12,21,43,54,45,36,27,18,19,10])
ab1=np.sort(ab)
ab1

array([10, 12, 18, 19, 21, 27, 36, 43, 45, 54])

In [60]:
ab3=np.flip(ab1)
ab3

array([54, 45, 43, 36, 27, 21, 19, 18, 12, 10])

In [61]:
# Array Filtering

In [62]:
ab=np.array([12,21,43,54])
ab1=[True,False,True,False]
New=ab[ab1]
New

array([12, 43])

In [68]:
new=[]
ab=np.array([12,21,43,54,45,36,27,18,19,10])
for x in ab:
    if x<40:
        new.append(True)
    else:
        new.append(False)
        
new

[True, True, False, False, False, True, True, True, True, True]